apiVersion: v1
kind: Service
metadata:
  name: nodeport-1128282732
spec:
  type: NodePort 
  selector:
    app: jeg-1128282732
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 80
      targetPort: 5000
